### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by DeverosTV** [jmej/MIDI2DMX#9]
hey, more than an issue is a question, did you try to use esp32 in this project as an alternative do teensy?
 if we talk about cost esp32 is cheaper
it also have a usb interface

**Comment by jmej** [comment]
@DeverosTV I haven't tried with an esp32, but I'm sure you could get something useful made using one! The PCB design only accommodates a teensy, but I would think the schematic and code would require little if any change if you're using hardware midi. That said, USB midi might be hard or impossible to do on an esp32. The teensy has usb-midi as a device type, I don't think the esp32 does -- but let me know if you figure it out!
